language: java

jdk:
  - openjdk8

script: mvn clean package

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'


before_deploy:
  - zip -r kworld-webservice *
  - mkdir -p deploy
  - mv kworld-webservice.zip deploy/kworld-webservice.zip     
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: kworld-webservice-deploy #S3 버킷 네임
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: KangPilGyu/kworld #Github 주소
      branch: alwaysUpdatePlz

- provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: kworld-webservice-deploy # S3 버킷
    key: kworld-webservice.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: kworld-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: KangPilGyu/kworld #Github 주소
      branch: alwaysUpdatePlz
      
# CI 실행 완료시 메일로 알람함
notifications:
  email:
    recipients:
      - eiffeltop01@gmail.com 