language: java
jdk:
  - openjdk8

branches:
  only:
    - alwaysUpdatePlz

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn test"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - eiffeltop01@gmail.com 